apiVersion: v1
kind: Service
metadata:
  name: cryptojackpot-app
  namespace: criptojackpot
  labels:
    app: cryptojackpot-app
    component: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: cryptojackpot-app
