apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# El namespace 'criptojackpot' es gestionado por el backend.
# No lo incluimos aqui para evitar conflictos de ownership.
resources:
  - frontend
