---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: criptojackpot
spec:
  encryptedData:
    NEXT_PUBLIC_GOOGLE_CLIENT_ID: AgBQxlmfvcHwkgkzYSDG9F+OgohVBrEpfT16dDjQmzHRkvYG/pEHuhSqeLCkzGsQWZhqkYJMCT1GvInv2gOkoh9OJEEIJ5w417+IMf7BE/oi6urNGRA2Bb4vsS2/wJ+7hHEX5eHmdMQffqAHlUFw3zP8+IjAf4FEFDSTyn5ZjtSd/LSXY0nbfVmsbxDZ3uOOVCoCEj77qKcZmgTukxaxnKsBvx2GiixLqc/ym7YywtImQBqnxjWGWJIMbXYGg71M70ayE+x3yqdskJitwlnXNP5HdXKE4+XXu47X1RqUBa1LUyqTbAwbu/gqEpqGzwhJqxlBLNRApSXb8UQwnZaaIKlHl/7fWoRXj1pA+o5GB71VSlX5jXy9dH4zyxSluElariOXrOQIelkUnEzvYMFA+FDPX756oOh4pB4okqUbK0hwE0P80ZhJyjsiXqBIRcgduOAZbAhu9n4STJT2OFzhqz4US0dI214zQIt49eNvEjtuZBbEVXIPXxklXeC0A2LKjHCJo4qXeXP4dvGPvnASmo7z2v0koV2xd2U492LjYk1xywVqszN0d9qFegQqJF2Qy4SLrNrwLgE8PuQWNskq1s0oOWry0EkifvnHaHDtqjQNx5T47vX4OY0qBtNyVPzrw3P1d1cjI+aKhue2eTTZVerpSpM1tvFXrMFT1FoAjtJoeTziM+Zt9CMpqspkyZMPgGpBuX+niQYjidvxjjwfUqmno68wzvc6n/sc+ZzHtHtueCtPutTkl4BXv8CFcLlhH7M3ivzNoz9Bd5RNCXmfxOWaz6QyYK478VQ=
  template:
    metadata:
      name: app-secrets
      namespace: criptojackpot
